# Generated by Django 6.0.5 on 2026-06-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAE', '0002_alter_absence_options_alter_cours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='groupe',
            options={'managed': True},
        ),
    ]
