# Generated by Django 6.0.5 on 2026-06-01 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'enseignant',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'etudiant',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'groupe',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('date_cours', models.DateField()),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('enseignant', models.ForeignKey(db_column='enseignant_id', on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='SAE.enseignant')),
                ('groupe', models.ForeignKey(db_column='groupe_id', on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='SAE.groupe')),
            ],
            options={
                'db_table': 'cours',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justifie', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True, null=True)),
                ('cours', models.ForeignKey(db_column='cours_id', on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='SAE.cours')),
                ('etudiant', models.ForeignKey(db_column='etudiant_id', on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='SAE.etudiant')),
            ],
            options={
                'db_table': 'absence',
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(db_column='groupe_id', on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='SAE.groupe'),
        ),
    ]
