# Generated by Django 6.0.5 on 2026-06-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAE', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='groupe',
            options={'managed': False},
        ),
    ]
